### ISSUE TITLE
Install won't enable in blender 2.82

### ISSUE THREAD

**Issue by mark-viatech** [ndee85/coa_tools#159]
Cloned the repo and zipped the coa_tools folder.  It installs but will not activate.  The error is:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Mark\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\coa_tools\__init__.py", line 145, in <module>
    create_sprite_object.COATOOLS_OT_CreateSpriteObject,
AttributeError: module 'coa_tools.operators.create_sprite_object' has no attribute 'COATOOLS_OT_CreateSpriteObject'

**Comment by tomaszjacek** [comment]
hi Mark,
Are you working with the 2.8 branch? 
It is needed by Blender 2.8.
tj

**Comment by shannon** [comment]
I had the same issue with the blender28 branch today. It works ok in 2.81 but 2.82a(downloaded today) throws the above error.

**Comment by mark-viatech** [comment]
Hi Tj & Shannon

Yes using the 2.80 branch the install gives that error.  I noticed that if I left the addon installed rather than removing it, and shut down Blender and reopened it the addon seemed to work OK. No idea what that means :)
Mark

**Comment by SirMeon** [comment]
Thank you mark! I was getting very frustrated searching for answers. Had the very same problem. But your suggestion worked: Install coa2.8, close/open Blender and then no error appears when enabling the COA-Tools checkbox! Thanks!!!!

**Comment by orlax** [comment]
Can confirm that closing and re-opening blender resolvers this issue, it seems that the python files / modules are not being recognized after installing. 

not sure how this could be fix thought.
